adobe-experience-league/exlm-converter

express.js
src/index.js
src/modules/ExlMd2Html.js
src/modules/blocks/create-badge.js
src/modules/blocks/create-code-block.js
src/modules/blocks/nested-blocks.js
src/modules/utils/dom-utils.js

This PR handles converting nested blocks into tables retroactively.
For each block converter, the converter need not worry weather the block is nested or not, conversion is agnostic to that.
After all block conversions are done, this PR looks up all blocks under main, with the specific selector `body > main > div > div` (top level blocks)
Then in each top-level block, it looks up blocks with specific classes (that has been converted already), and converts them to specifically structured tables. Each of these tables would have the block classes as headers, and each row in that block would be a table row.

EXLM-172 - Convert all nested blocks into tables

---

src/modules/ExlMd2Html.js
src/modules/blocks/create-mini-toc.js

EXLM-209: revised solution | converter creates a div stub only and franklin blocks has rest of logic.

EXLM-209: revised solution | converter creates a div stub only and franklin blocks has rest of logic.

---

src/index.js
src/modules/ExlClient.js
src/modules/ExlMd2Html.js
src/url-mapping.js

This PR moves away from using url mapping to using the EXL API to lookup docs by path, for example:
Looking up the article for this doc: https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/caching/author.html?lang=en
Can be done with:
https://experienceleague.adobe.com/api/articles?URL=https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/caching/author.html?lang=en
For internal pages, we will continue to use a url mapping until a more permanent solution is implemented.

Use URL article API and use mapping for internal URLs only

---

src/modules/ExlMd2Html.js

AMF has a bug where it doesn't handle tripple-backticks correctly. it assumes ALL backticks are the start/end of a code block. in some doc markdowns, we saw a few ``` in the middle of a sentence. this PR fixes that by encoding the backticks that are not preceded with a new line before passing to AMF, and then decoding them after.

EXLM-290 - Handle issue where amf considers all triple backticks as start of code block

---

.github/workflows/deploy-action.yaml
.gitignore
README.md
app.config.yaml
build/express.js
package-lock.json
package.json
src/aem-config.js
src/index.js
src/renderers/render-aem.js
src/renderers/render-doc.js
src/renderers/render-fragment.js

1. Refactor Action code, separate each renderer to their own file
2. Move AEM configurations from a JS file in the repo, to environment variables instead - and update the github action and the local express server and docs for both.

Move AEM Configurations to Environment Variables

---

build/express.js
src/index.js
src/modules/utils/media-utils.js
src/renderers/render-aem.js
src/renderers/render-doc.js
src/renderers/render-fragment.js

Renderers are now required to return `body` and `headers` instead of `html`
This is to handle binary and non-html responses like JSON or text
Also return proper `Content-Type` headers and pass-through the `Content-Type` for AEM rendering

Make renderers API generic and pass-through content-type header

---

src/modules/ExlMd2Html.js
src/modules/blocks/create-breadcrumbs.js

The PR has been raised based on the comment by Ahamed in https://jira.corp.adobe.com/browse/EXLM-280 i.e at the moment the breadcrumb converter has been written based on the mock json metadata which is expected from page API response. 
We need to revisit the breadcrumbs once the correct API response is available.

breadcrumbs converter

---

src/url-mapping.js

Preview API call failing on internal pages and returning 502 error from content bus.
Seems like the ids got updated in ExL site.
E.g: https://experienceleague.corp.adobe.com/docs/authoring-guide-exl/using/markdown/cheatsheet.html?lang=en
id is now updated to "recrXgJulsTnJcffM"
Fix : Updated ids for the internal pages in url-mappings.js

Updated id for internal Urls

---

.github/workflows/deploy-action.yaml

UE publishing blocked as the GH Action picking the current branch name for fetching the content from AEM. Created a new repo variable called BRANCH and updated the action to pass on the variable to converter runtime.

deploy-action update with BRANCH variable on stage

---

src/converter/modules/utils/link-utils.js

In case of URLs like
/docs/target-learn/tutorials/administration/strategy/1.1-implementation-strategy-sys-governance.html?lang=en, /docs/target-learn/tutorials/implementation/2.1-intro-to-target-implementation.html?lang=en ,
/docs/target-learn/tutorials/integrations/3.2-target-analytics.html?lang=en
strings after . are getting removed.
https://main--exlm--adobe-experience-league.hlx.live/en/docs/target 
Added condition if extension is .html or .md, then calling the removeExtension() method.

Fixed anchor links

---

src/converter/modules/ExlClient.js
src/converter/renderers/render-landing.js

1. Updated correct lang (case-sensitive) for Landing API as the existing API call wasn't returning translated content for pt-br, zh-hans and zh-hant.
2. Added 404 for landing pages that do not exist in Landing API response.
https://experienceleague.adobe.com/api/landing-pages?lang=en&page_size=100

404 for invalid solution landing pages

---

src/converter/modules/utils/language-utils.js
src/converter/modules/utils/link-utils.js

The links are not rendered correctly for non-english pages. E.g. https://main--exlm--adobe-experience-league.hlx.page/ko/docs/analytics
Its pointing to /ko-kr/ instead of /ko/

Corrected links for all languages

---

src/converter/modules/ExlClient.js

This PR ensures that the converter resolves articles even if the article path has upper case chars; by using the new `Search URL` param of the EXL API.

Return /docs Article regardless of path case sensitivity 

---

src/converter/modules/ExlMd2Html.js
src/converter/modules/utils/update-anchors.js

the helix html2md pipeline diregards any "id" attributes on headers (and other els I believe). so we need a way for these ids to survive the html2md pipeline. These IDs are used as anchors. This PR solves that issue. see: `src/converter/modules/utils/update-anchors.js`

Add anchors as icon suffixes

---

src/converter/modules/utils/link-utils.js

For Docs landing page, updated links for courses and support.
If courses link starts with /#courses, updating it to **/home#courses**
If support link starts with /?support-solution=General&support-tab=home#support, updating to **/home?support-solution=General&support-tab=home#support**

Updated logic based on page type

---

src/converter/renderers/render-landing.js

Currently "/en/docs/home" is rendered as a solution landing page.
https://eds-stage.experienceleague.adobe.com/en/docs/home
Updated logic to render solution name "home" as Docs landing page.

EXLM-1197 Docs Landing page

---

src/converter/renderers/render-fragment.js

https://jira.corp.adobe.com/browse/EXLM-1432
Added noindex & nofollow rules to all EDS fragments so these pages are not indexed.

EXLM-1432 No-index no-follow for fragments

---

app.config.yaml
build/build-helpers.js
package-lock.json
package.json
src/common/utils/publish-util.js
src/converter/modules/ExlMd2Html.js
src/converter/modules/blocks/too-many-images.js
src/converter/modules/utils/dom-utils.js
src/converter/modules/utils/file-utils.js
src/converter/modules/utils/local-files.js
src/converter/modules/utils/prettier-utils.js
src/converter/renderers/render-aem-asset.js
src/converter/renderers/render-doc.js
src/converter/renderers/render-fragment.js
src/publish/index.js

see: https://www.aem.live/docs/limits#byom-content-source-limits
The max number of unique images for a page is 100 image.
To get around this, this PR creates a new fragment whose content is everything after the 100th image, while maintaining content within sections.
This is NOT an encouragement to build pages with more than 100 images. But rather an exception for pages that currently exist and have 100 image in them.
Internally, there is validation to tell authors to avoid creating pages with large number of images.

Automatically create create (and publish) fragments when page has over 100 images

---

build/express.js
src/converter/modules/utils/local-files.js
src/converter/renderers/render-aem.js

Responses from AEM, like redirects.json might be larger than 1mb.
1mb is the limit for Adobe IO action payload.
this PR writes the AEM response to AIO files, then returns a redirect to the presigned URL of that file.

serve AEM responses that are larger than 1MB

---

src/converter/modules/utils/update-anchors.js

this is due to: adobe/helix-html-pipeline@76f37b0#diff-5d793c559c53235e431b1b6be412b7cb136add07bc5095f0aa7ec8036f96f878R16
this same change is also in Dev/stage but needed to be in prod immediately.

Hotfix: UGP-11928: fix header anchor not rendered as an icon

---

src/converter/static/fragments/de/footer/footer.html
src/converter/static/fragments/en/footer/footer.html
src/converter/static/fragments/es/footer/footer.html
src/converter/static/fragments/es/header/header.yaml
src/converter/static/fragments/fr/footer/footer.html
src/converter/static/fragments/it/footer/footer.html
src/converter/static/fragments/ja/footer/footer.html
src/converter/static/fragments/ko/footer/footer.html
src/converter/static/fragments/nl/footer/footer.html
src/converter/static/fragments/pt-br/footer/footer.html
src/converter/static/fragments/sv/footer/footer.html
src/converter/static/fragments/zh-hans/footer/footer.html
src/converter/static/fragments/zh-hant/footer/footer.html

1. UGP-8123 [Footer] String "Cookie preferences" is not localized on corresponding locale in Footer
2. UGP-11732 [Documentation][LOC] 'Tutorials' string is unlocalized in footer
3. UGP-9655 [Footer] Strings 'Adobe Developer' and 'COVID-19 Responses' appear unlocalized in footer
4. UGP-8087 [Footer]: Category pages: Community, Support, Adobe  lead to the English locale
5. UGP-8086 [Footer]: "Document Cloud release notes" link lead to page with incorrect locale. 
6. UGP-8089 [Footer]: "Privacy", "Terms of Use", "Do not sell my personal information", "AdChoices" links are leads to pages with incorrect locale
7. UGP-9656 [Footer] Adobe Status product name starts with lowercase letter in footer
8. UGP-9958 [Footer][ESP,PTB] Products name starts with lowercase letter in footer
9. UGP-12469 …

UGP-Task-Batch Minor updates and localization issues.

---

src/converter/static/fragments/en/footer/footer.html

Jira Ticket: UGP-12701
The 'COVID-19 Responses' link in the footer menu, under the 'Adobe' column, points to a non-existent page. It should be removed.

bugfix/UGP-12701 Remove COVID link from the english footer

---

src/converter/modules/blocks/create-highlight.js

The helix html2md conversion does not respect suffix/prefix spaces inside a <u>, so we move those spaces to the surrounding <em> instead; helix html2md conversion respects that.

fix: (UGP-11508) properly handle whitespacing for highlighted text

---

src/converter/modules/ExlMd2Html.js
src/converter/modules/blocks-translated-labels.js
src/converter/modules/blocks/create-article-metadata-appliesto.js

Jira Task UGP-9959
**Description:** Add a new 'Applies to' block on document pages that displays version metadata. The block shows the version information under a localized "APPLIES TO" heading
Testing URLS:
$env/en/docs/internal-test/test/bug-fixes/validation-notes
$env/en/docs/internal-test/test/table-spans
$env/en/docs/internal-test/test/feature-testing/downloads
$env/en/docs/internal-test/test/bug-fixes/zoomable-images-tables
$env/en/docs/internal-test/test/bug-fixes/validation-notes
$env/en/docs/internal-test/test/feature-testing/ugp-11565

feature UGP-8889 Adding applies to block

---

src/converter/modules/blocks/create-article-metadata-appliesto.js

Jira Task UGP-9959
**Description:** Add a new 'Applies to' block on document pages that displays version metadata. The block shows the version information under a localized "APPLIES TO" heading
What Changes: HTML structure to use same css declarations of the topics block
Testing URLS:
$/en/docs/internal-test/test/bug-fixes/validation-notes
$/en/docs/internal-test/test/table-spans
$/en/docs/internal-test/test/feature-testing/downloads
$/en/docs/internal-test/test/bug-fixes/zoomable-images-tables
$/en/docs/internal-test/test/bug-fixes/validation-notes
$/en/docs/internal-test/test/feature-testing/ugp-11565

Feature/UGP-8889 "Applies to" html structure changed.
