adobe-experience-league/exlm-converter

- src/modules/ExlMd2Html.js
- src/modules/blocks/create-tabs.js
[EXLM-91](https://jira.corp.adobe.com/browse/EXLM-91) Tabs block
> EXLM-91 Tabs block

- src/modules/blocks/create-tabs.js
- src/url-mapping.js
[EXLM-91](https://jira.corp.adobe.com/browse/EXLM-91) Tabs block
> Update tabs block to render tab contents as html

- src/index.js
- src/modules/ExlMd2Html.js
- src/modules/utils/dom-utils.js
JIRA: https://jira.corp.adobe.com/browse/EXLM-87
> Generate metadata from API response

- src/modules/ExlMd2Html.js
- src/modules/blocks/create-list.js
[EXLM-187](https://jira.corp.adobe.com/browse/EXLM-187) Lists
> EXLM-187 Lists

- src/modules/blocks/create-tables.js
- src/url-mapping.js
Table block handled with layout-fixed and layout-auto use case.
And MD table as well captured.
> table add layout variation

- src/modules/ExlMd2Html.js
- src/modules/utils/dom-utils.js
JIRA: https://jira.corp.adobe.com/browse/EXLM-270
> Update URL to handle external links

- src/modules/utils/link-utils.js
- Removes the ".html" extension from the last segment of a URL's path.
> handle extension for franklin URLs

- src/modules/ExlMd2Html.js
- src/modules/blocks/create-img-block.js
Jira https://jira.corp.adobe.com/browse/EXLM-321
> Image block EXLM-321

- src/index.js
- src/modules/ExlMd2Html.js
- src/modules/blocks/create-article-metadata-createdby.js
Modified the existing code for extracting the CreatedBy data from meta tags to Level and  Role keys according to latest confirmation from EXLM Team
https://jira.corp.adobe.com/browse/EXLM-286
Reference URL:https://experienceleague-dev.corp.adobe.com/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers.html?lang=en
Franklin Published URL: https://main--exlm--devisree29.hlx.page/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers
> Bugfix EXLM 286 Createdby Data

- src/modules/ExlMd2Html.js
- src/modules/blocks/create-accordion.js
- src/modules/blocks/nested-blocks.js
- src/url-mapping.js
accordion converter. includes changes per PR review of original branch ([feature/EXLM-83-accordion](https://github.com/adobe-experience-league/exlm-converter/pull/59))
> EXLM-83: accordion converter. includes changes per PR review of original branch (feature/EXLM-83-accordion)

- src/modules/blocks/create-accordion.js
Handles case where accordion was authored as HTML (not collapsible MD)
> EXLM-83 Handle HTML authored accordion

- .github/workflows/deploy-action.yaml
- build/ensure-env.js
- build/express.js
- build/publish-fragments.js
... and use github context for ref name
> Ensure express variables and build variables separately

- src/modules/blocks/create-img-block.js
- src/modules/blocks/nested-blocks.js
Creating a custom block for img when parameters present. Setup in such a way to escape helix pipe.
> Creating custom block for img

- src/fragments/en/footer/footer.html
- src/fragments/en/header/learn.html
- src/fragments/en/header/topnav.html
Updated header and footer content as per XD.
1. Removed Business solutions section
2. Segregated learn menu for desktop and mobile
> EXLM-395 Content update

- src/modules/ExlClient.js
- src/modules/ExlMd2Html.js
- src/modules/utils/dom-utils.js
Added new param **Keywords** as part of src/modules/ExlClient.js to extract Keywords from API
Updated the method **createMetaData()** to accpet data as param in src/modules/ExlMd2Html.js
Updated the method **createMetaData()**  to parse data in Yaml Format and added new metadata extraction params Id and Keywords. 
Sample Reference URL:https://experienceleague.adobe.com/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers.html?lang=en
Published Franklin URL: https://main--exlm--devisree29.hlx.page/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers
> EXLM 261 Clue Template

- src/modules/blocks/create-article-metadata-createdby.js
There is a requirement to update the created by metadata HTML structure as mentioned in https://jira.corp.adobe.com/browse/EXLM-458.
> created by metadata update

- src/modules/blocks/create-article-metadata-createdby.js
Added checks for empty strings.
> EXLM-279 Created For Block

- src/modules/blocks/create-doc-actions.js
Fix for doc action render logic
> doc-action-render

- src/fragments/en/feedback-bar/feedback-bar.html
[EXLM-496](https://jira.corp.adobe.com/browse/EXLM-496) Feedback bar fragment
Created a feedback-bar fragment under src/fragments/en folder.
> EXLM-496 Feedback bar fragment

- src/fragments/en/header/header.yaml
EXLM 25 Header Search Filters
Updated header.yaml to include Troubleshooting Filter
https://jira.corp.adobe.com/browse/EXLM-25
https://main--exlm--devisree29.hlx.page/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers#
> EXLM 25 Header Search Filters

- src/fragments/en/header/header.html
- src/fragments/en/header/header.yaml
- src/renderers/utils/ejs-utils.js
Product Grid (before sign in Link) inclusion in header navigation
> product-grid-inclusion

- .github/workflows/deploy-action.yaml
see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
> update action to deploy based on Env/branch - Use Env Files

- src/fragments/en/dashboard/preferences.html
Include for Dashboard -> Profile(preferences) fragment
> exlm-821-preferences

- src/doc-page-types.js
- src/modules/ExlMd2Html.js
- src/modules/blocks/create-cloud-solutions.js
- src/renderers/render-doc.js
- src/renderers/render-landing.js
Defined pageType for doc landing, solution landing and article pages.
> EXLM-939 Structure to deal with different page types

- src/doc-page-types.js
- src/modules/ExlMd2Html.js
- src/modules/blocks/create-guides-list.js
- src/modules/blocks/create-related-resources.js
- src/modules/blocks/create-tutorial-tiles.js
- src/renderers/render-doc.js
- src/renderers/render-landing.js
Added blocks for Solutions Landing page.
Guides List : https://jira.corp.adobe.com/browse/EXLM-933
Tutorial tiles: https://jira.corp.adobe.com/browse/EXLM-934
Related resources : https://jira.corp.adobe.com/browse/EXLM-935
> EXLM-889 Blocks for Solution landing page

- src/doc-page-types.js
- src/modules/blocks/create-cloud-solutions.js
> EXLM-976 Cloud solutions block

- .github/workflows/deploy-action.yaml
Updating env var reference in workflows
> env-var-reference-update

- src/converter/modules/utils/link-utils.js
- src/converter/modules/utils/path-utils.js
- src/converter/renderers/render-doc.js
Added regex to check path extensions instead of hardcoding to .html and .md
> Added regex to check for path extensions

- src/converter/static/fragments/en/header/header.yaml
Moved Certifications from top nav to under Learn, Tutorials
> EXLM-1032 Header - Moved Certification under Learn

- src/converter/modules/ExlMd2Html.js
- src/converter/modules/utils/dom-utils.js
Updated Page Title as per EXL site.
Converter:
> EXLM-1071 SEO - Maintain Page Titles to match current EXL site

- src/converter/modules/blocks/create-article-metadata-createdby.js
- src/converter/modules/blocks/create-breadcrumbs.js
Added check to remove empty Created For:
Added breadcrumbs as the first element under main div
> EXLM-1092 UI Fixes for Created For and Breadcrumbs

- src/converter/index.js
Added optional chaining for error code as its causing undefined error and AIO isn't working.
> Fixed undefined issue for error code

- src/converter/modules/blocks/create-article-metadata-createdby.js
- src/converter/modules/blocks/create-badge.js
Added a common class 'same-p-tag' for badge blocks wrapped inside a single p tag for styling purpose.
> EXLM-1092 UI Fixes for Created For and Badge block

- src/converter/modules/utils/dom-utils.js
the exl api returns both robots and ROBOTS for hidden pages, this PR combines them into one meta.
> Consolidate robots and ROBOTS meta

- src/converter/modules/ExlMd2Html.js
- src/converter/modules/blocks/create-staff-picks-block.js
> EXLM-1147 Staff Picks block

- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.yaml
https://jira.corp.adobe.com/browse/UGP-10306
> Browse all courses links fix

- src/converter/modules/blocks/create-target-insertion.js
... and supports nested divs whose id also starts with `rec-`; up to 1 level of nesting.
> UGP-10237 - Target Insertion Point is now any div element whose id starts with `rec-`

- src/converter/modules/blocks/create-target-insertion.js
... and supports nested divs whose id also starts with rec-; up to 1 level of nesting.
> UGP-10237 - Target Insertion Point is now any div element whose id starts with rec-

- src/converter/static/fragments/de/header/header.html
- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/header/header.html
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/header/header.html
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/header/header.html
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/header/header.html
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/header/header.html
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/header/header.html
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/header/header.html
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.html
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/header/header.html
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/header/header.html
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.html
- src/converter/static/fragments/zh-hant/header/header.yaml
Removed Sign in block.
Updated Sign up to Sign In.
> EXLM-1193 Converter changes for sign up

- src/converter/renderers/render-aem.js
* EXLM-1213: make image meta tag absolute
* fix: format
> develop -> stage

- src/converter/static/fragments/fr/footer/footer.html
- src/converter/static/fragments/fr/header/header.yaml
Updated translated header content for FR language based on fragments spreadsheet.
https://author-p122525-e1219192.adobeaemcloud.com/content/exlm/global/fr/fragments.html
> EXLM-1199 Updated translated content for header for FR language

- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.yaml
Updated header content for pt-BR, ko and zh-hant
> EXLM-1242 Prod Hotfix - header translated content

- src/converter/modules/ExlClient.js
- src/converter/modules/blocks/create-breadcrumbs.js
- src/khoros/utils/IMSService.js
fix: do not cache stateful objects in module scope
> fix: do not cache stateful objects in module scope

- src/converter/renderers/render-aem.js
> EXLM-1444 no index rule added for author bio pages

- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.yaml
> EXLM-1481 Added article content type for header search

- src/converter/modules/ExlClient.js
- src/converter/modules/ExlMd2Html.js
- src/converter/modules/blocks/create-article-metadata-createdby.js
- src/converter/modules/blocks/create-article-metadata-topics.js
We probably don't need to go through a complete doc rebuild yet for this because there may be a few other changes related to discoverability v1.2.
> UGP-9709: Translate metadata tags 

- src/khoros/utils/KhorosProxy.js
Added a new path under ALLOWED_PATHS for a new endpoint to fetch profile info in Khoros Proxy
https://jira.corp.adobe.com/browse/COMM-2840
> EXLM 1505 Profile Card

- .github/workflows/deploy-action.yaml
- app.config.yaml
- src/common/utils/publish-util.js
see: https://github.com/adobe-experience-league/exlm-converter/pull/367
> UGP-10894 Add APi Key

- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.yaml
Updated "Actionable Insights" to "Perspectives" in header search dropdown
> EXLM-1775 Header search dropdown update

- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/header/header.yaml
Reverts adobe-experience-league/exlm-converter#386
> Revert "EXLM-1881 Added urlOption for perspectives"

- build/publish-fragments.js
see: https://www.aem.live/docs/limits#admin-api-limits
> Admin API Rate Limit - ensure max 10/second requests are sent to admin API

- src/converter/static/fragments/de/footer/footer.html
- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/footer/footer.html
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/footer/footer.html
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/footer/footer.html
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/footer/footer.html
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/footer/footer.html
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/footer/footer.html
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/footer/footer.html
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/footer/footer.html
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/footer/footer.html
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/footer/footer.html
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/footer/footer.html
- src/converter/static/fragments/zh-hant/header/header.yaml
Updated profile links post PHP implementation.
> Updated PHP links in header footer

- src/converter/modules/utils/update-anchors.js
this is due to: https://github.com/adobe/helix-html-pipeline/commit/76f37b0041d1e10b7c44e53348517359f054f356#diff-5d793c559c53235e431b1b6be412b7cb136add07bc5095f0aa7ec8036f96f878R16
> UGP-11928: fix header anchor not rendered as an icon

- src/converter/renderers/render-aem.js
This reverts commit e548282843cc7bb6b439a09aa202d5427194cda6.
> Revert "disable new tags feature due to perf issues"

- src/converter/renderers/render-aem.js
Reverts adobe-experience-league/exlm-converter#465
> Revert "Revert "disable new tags feature due to perf issues""

- src/converter/static/fragments/de/footer/footer.html
- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/footer/footer.html
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/footer/footer.html
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/footer/footer.html
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/footer/footer.html
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/footer/footer.html
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/footer/footer.html
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/footer/footer.html
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/footer/footer.html
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/footer/footer.html
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/footer/footer.html
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/footer/footer.html
- src/converter/static/fragments/zh-hant/header/header.yaml
Reverts adobe-experience-league/exlm-converter#495
> Revert "EXLM-3065 Events link updated for Header and Footer"

- src/converter/static/fragments/en/footer/footer.html
English link change (Panel -> Program)
> feature/UGP-12729 English Panel changes

- src/converter/static/fragments/de/footer/footer.html
- src/converter/static/fragments/de/header/header.yaml
- src/converter/static/fragments/en/footer/footer.html
- src/converter/static/fragments/en/header/header.yaml
- src/converter/static/fragments/es/footer/footer.html
- src/converter/static/fragments/es/header/header.yaml
- src/converter/static/fragments/fr/footer/footer.html
- src/converter/static/fragments/fr/header/header.yaml
- src/converter/static/fragments/it/footer/footer.html
- src/converter/static/fragments/it/header/header.yaml
- src/converter/static/fragments/ja/footer/footer.html
- src/converter/static/fragments/ja/header/header.yaml
- src/converter/static/fragments/ko/footer/footer.html
- src/converter/static/fragments/ko/header/header.yaml
- src/converter/static/fragments/nl/footer/footer.html
- src/converter/static/fragments/nl/header/header.yaml
- src/converter/static/fragments/pt-br/footer/footer.html
- src/converter/static/fragments/pt-br/header/header.yaml
- src/converter/static/fragments/sv/footer/footer.html
- src/converter/static/fragments/sv/header/header.yaml
- src/converter/static/fragments/zh-hans/footer/footer.html
- src/converter/static/fragments/zh-hans/header/header.yaml
- src/converter/static/fragments/zh-hant/footer/footer.html
- src/converter/static/fragments/zh-hant/header/header.yaml
Jira ID: UGP-13018
Updates for url links on header and footer for the new feedback program page redesign. https://experienceleague.adobe.com/en/feedback-program
> UGP-13018 Feedback program links update

- src/common/utils/doc-page-types.js
- src/converter/modules/ExlClient.js
- src/converter/modules/utils/metadata-util.js
- src/converter/renderers/playlists/create-playlist.js
- src/converter/renderers/playlists/types.js
- src/converter/renderers/render-playlist.js
Reverts adobe-experience-league/exlm-converter#530
> Revert "feat: (UGP-12942) render playlists from new playlists API"

- src/converter/index.js
- src/converter/renderers/render-playlist.js
After deploying this PR -https://github.com/adobe-experience-league/exlm-converter/pull/537/files#diff-f7934d5041ba161175f0cfaee7a0cbbe951650e113473843351da743ac8f13d0
we encountered an issue with AEM publishing.
As a temporary workaround, made the following code adjustments.
> Authorization code fixes

- src/converter/renderers/utils/hash-quiz-answers.js
Change in structure of quiz block, hence updating the hash answers util to process questions
> Process questions
